.\" Manpage for Houndsniff

.TH man 8 "10 Mar 2021" "1.5" "Houndsniff manual page"
.SH NAME
Houndsniff \- Hash algorithm identification
.SH SYNOPSIS
houndsniff [HASH]
.SH DESCRIPTION
Houndsniff is a hash recognition/identification program. It works by extracting two main characteristics about the the hash and comparing it to characteristics of hashes produced by different hashing algorithms stored in a local database. Then, it prints the matches sorted by popularity. The popularity of each hashing algorithm is determined by web search result numbers in comparison to other hashes with the same characteristcs. These characteristics are length and character set.

Current version: 1.5

.B
If your hash includes a dollar sign ($), make sure you place it in between quotes.


Send missing hashes at
.I
houndsniff@protonmail.com
or contribute to the github project:
.I
https://github.com/MichaelDim02/houndsniff

.SH OPTIONS
-h	display help panel & exit

-l	list supported hashing algorithms
.SH AUTHOR
Michael Constantine Dimopoulos et al

.LP
Contributors: 
.LP
Christopher Wellons,
.LP
Martin K.
.LP
tuu & fizzie on ##c@freenode

.SH LICENSE
GNU Public License 3.0 (GPL-3.0)
